### ISSUE TITLE
Please, specify what is cycle?

### ISSUE THREAD

**Issue by Hombre2014** [PerxTech/backend-interview#3]
In the Loyalty Rules section under Tier 2 there is the following sentence:

2. Loyalty tiers are calculated on the highest points in the last 2 cycles

It does not specify what is a cycle. Is it a month? Please, specify what the cycle is.

**Comment by rationality6** [comment]
Yes, I have the same problem with modeling

**Comment by gocanto** [comment]
We are working on these updates atm.
We will update them once we have the simplest approach for this exercise.
